## Making predictions using an ml model

2 ways to make predictions:
* predict()
* predict_proba()

In [34]:
import pandas as pd
heart_disease=pd.read_csv("data/heart-disease.csv")
heart_disease.head(5)

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [35]:
# Import the RandomForestClassifier estimator class
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split

# Setup random seed
import numpy as np
np.random.seed(42)

# Make the data
X= heart_disease.drop("target", axis=1)
Y=heart_disease["target"]

# Split the data
X_train, X_test, Y_train, Y_test= train_test_split(X, Y, test_size=0.2)

# Instantiate RandomForestClassifier
clf=RandomForestClassifier()

# Fit the model to the data (training the ml model) 
clf.fit(X_train, Y_train)

# Evaluate the RandomForestClassifier (use the patterns the model has created)
clf.score(X_test, Y_test)   # the model is making predictions on some X_test, actually making Y_pred and then comparing it with Y_test

0.8524590163934426

 M1. Making predictions using predict()

In [36]:

# Use a trained model to make predictions
clf.predict(np.array([1,2,3,4]))    # this doesn't work

c:\Users\ftska\Documents\sample_project_2\python_venv\lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


ValueError: Expected 2D array, got 1D array instead:
array=[1. 2. 3. 4.].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [ ]:
clf.predict(X_test)

array([0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0], dtype=int64)

In [ ]:
np.array(Y_test)

array([0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0,
       0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0], dtype=int64)

In [ ]:
# predictions are in the same format as our Y_test

In [ ]:
# Compare predictions to truth labels (Y) to evaluate the model
# M1.
Y_preds=clf.predict(X_test)
np.mean(Y_preds==Y_test)

0.8688524590163934

In [ ]:
# M2.
clf.score(X_test, Y_test)

0.8688524590163934

In [ ]:
# M3.
from sklearn.metrics import accuracy_score
accuracy_score(Y_test, Y_preds)

0.8688524590163934

 M2.
 Maklng predictions using predict_proba()

In [37]:
# predict_proba() returns probabilities of a classification label
clf.predict_proba(X_test[:4])


array([[0.89, 0.11],
       [0.49, 0.51],
       [0.43, 0.57],
       [0.84, 0.16]])

In [38]:
# LinearSVC object has no attribute "predict_proba()"

In [39]:
# predict() on the same data
clf.predict(X_test[:4])

array([0, 1, 1, 0], dtype=int64)

In [ ]:
# predict()- will give u a single label for each sample
# predict_proba()- returns the probabilities of a classification label