Regression  model evaluation metrics
The one's we are going to cover-
* R^2(pronounced R-squared) or coefficient of determination
* Mean absolute error(MAE)
* Mean Squared error(MSE)

R^2- Compares your model prediction to the mean of the targets. Values can range from negative infinite (more poor model) to 1
For example if all your model does is predict the mean of the targets, its r^2 value would be 0 and if your model perfectly predicts the range of numbers its r^2 value is 1.

In [1]:
from sklearn.datasets import fetch_california_housing
housing=fetch_california_housing()
housing

{'data': array([[   8.3252    ,   41.        ,    6.98412698, ...,    2.55555556,
           37.88      , -122.23      ],
        [   8.3014    ,   21.        ,    6.23813708, ...,    2.10984183,
           37.86      , -122.22      ],
        [   7.2574    ,   52.        ,    8.28813559, ...,    2.80225989,
           37.85      , -122.24      ],
        ...,
        [   1.7       ,   17.        ,    5.20554273, ...,    2.3256351 ,
           39.43      , -121.22      ],
        [   1.8672    ,   18.        ,    5.32951289, ...,    2.12320917,
           39.43      , -121.32      ],
        [   2.3886    ,   16.        ,    5.25471698, ...,    2.61698113,
           39.37      , -121.24      ]]),
 'target': array([4.526, 3.585, 3.521, ..., 0.923, 0.847, 0.894]),
 'frame': None,
 'target_names': ['MedHouseVal'],
 'feature_names': ['MedInc',
  'HouseAge',
  'AveRooms',
  'AveBedrms',
  'Population',
  'AveOccup',
  'Latitude',
  'Longitude'],
 'DESCR': '.. _california_housing_dataset:\n

In [2]:
import pandas as pd
housing_df=pd.DataFrame(housing["data"], columns=housing["feature_names"])
housing_df.head(5)

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0  8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1  8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2  7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3  5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4  3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   

   Longitude  
0    -122.23  
1    -122.22  
2    -122.24  
3    -122.25  
4    -122.25

In [3]:
housing_df["target"]=housing["target"]
housing_df.head(3)

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0  8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1  8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2  7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   

   Longitude  target  
0    -122.23   4.526  
1    -122.22   3.585  
2    -122.24   3.521

In [4]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
import numpy as np
np.random.seed(42)
X=housing_df.drop("target", axis=1)
Y=housing_df["target"]
X_train, X_test, Y_train, Y_test= train_test_split(X, Y, test_size=0.2)
model=RandomForestRegressor(n_estimators=100)
model.fit(X_train, Y_train)


RandomForestRegressor()

In [5]:
model.score(X_test, Y_test)

0.8065734772187598

In [6]:
housing_df.head(3)

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0  8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1  8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2  7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   

   Longitude  target  
0    -122.23   4.526  
1    -122.22   3.585  
2    -122.24   3.521

In [7]:
Y_test

20046    0.47700
3024     0.45800
15663    5.00001
20484    2.18600
9814     2.78000
          ...   
15362    2.63300
16623    2.66800
18086    5.00001
2144     0.72300
3665     1.51500
Name: target, Length: 4128, dtype: float64

In [8]:
Y_test.mean()

2.0550030959302323

In [9]:
from sklearn.metrics import r2_score
Y_test_mean=np.full(len(Y_test), Y_test.mean())
Y_test_mean[:3]

array([2.0550031, 2.0550031, 2.0550031])

In [10]:
r2_score(y_true=Y_test, y_pred=Y_test_mean)

0.0

In [11]:
r2_score(y_true=Y_test, y_pred=Y_test)

1.0

MAE- Average of the absolute differences between predicted and the actual values.
It gives you an idea how wrong your model predictions are

In [12]:
from sklearn.metrics import mean_absolute_error
Y_preds=model.predict(X_test)
mae=mean_absolute_error(Y_test, Y_preds)
mae

0.32659871732073664

In [13]:
Y_preds

array([0.49384  , 0.75494  , 4.9285964, ..., 4.8363785, 0.71782  ,
       1.67901  ])

In [14]:
Y_test

20046    0.47700
3024     0.45800
15663    5.00001
20484    2.18600
9814     2.78000
          ...   
15362    2.63300
16623    2.66800
18086    5.00001
2144     0.72300
3665     1.51500
Name: target, Length: 4128, dtype: float64

In [15]:
df=pd.DataFrame(data={"actual_values": Y_test, "predicted_values":Y_preds})
df["differences"]=df["predicted_values"]-df["actual_values"]
df.head(10)

actual_values  predicted_values  differences
20046        0.47700          0.493840     0.016840
3024         0.45800          0.754940     0.296940
15663        5.00001          4.928596    -0.071414
20484        2.18600          2.543160     0.357160
9814         2.78000          2.331760    -0.448240
13311        1.58700          1.652530     0.065530
7113         1.98200          2.343230     0.361230
7668         1.57500          1.661820     0.086820
18246        3.40000          2.474890    -0.925110
5723         4.46600          4.834478     0.368478

In [16]:
df["differences"].mean()       # absolute of differnces is not taken care 

0.012048392126937589

In [17]:
np.abs(df["differences"]).mean()

0.32659871732073664

MSE-mean of the square of the errors between actual and the predicted ones 


In [18]:
from sklearn.metrics import mean_squared_error
Y_preds=model.predict(X_test)
mse=mean_squared_error(Y_test, Y_preds)
mse

0.2534678520824551

In [19]:
df["squared_differences"]=np.square(df["differences"])
df.head()

actual_values  predicted_values  differences  squared_differences
20046        0.47700          0.493840     0.016840             0.000284
3024         0.45800          0.754940     0.296940             0.088173
15663        5.00001          4.928596    -0.071414             0.005100
20484        2.18600          2.543160     0.357160             0.127563
9814         2.78000          2.331760    -0.448240             0.200919

In [20]:
squared=np.square(df["differences"])
squared.mean()

0.2534678520824551

Let's see the scoring parameter being used for a regression problem


In [21]:
from sklearn.model_selection import cross_val_score
from sklearn.ensemble import RandomForestRegressor
import numpy as np
np.random.seed(42)
X=housing_df.drop("target", axis=1)
Y=housing_df["target"]
model=RandomForestRegressor()

In [22]:
np.random.seed(42)
cv_r2=cross_val_score(model, X, Y, cv=5, scoring=None)
np.mean(cv_r2)


0.6520824166120266

In [23]:
cv_r2

array([0.51682388, 0.70279716, 0.74197717, 0.61638204, 0.68243183])

In [24]:
# Mean Squared Error
cv_mse=cross_val_score(model, X, Y, cv=5, scoring="neg_mean_squared_error")
np.mean(cv_mse)

-0.43099502243995547

In [25]:
cv_mse

array([-0.51296289, -0.35070541, -0.37298376, -0.44907837, -0.46924468])

In [26]:
# Mean Absolute Error
cv_mae=cross_val_score(model, X, Y, cv=5, scoring="neg_mean_absolute_error")
np.mean(cv_mae)

-0.46446241455910864

In [27]:
cv_mae

array([-0.54535682, -0.405814  , -0.43474105, -0.46311862, -0.47328158])